// Command docsgen renders docs/reference from the tables agentfs itself reads.
//
// A reference kept by hand drifts from the code it describes. Every page here
// is rendered from the Go table the running program consults — the command
// table, the limit table, the exit-code registry, the binding table, the
// diagnostic registry and the state contract — so a page and the behaviour it
// documents cannot disagree. "task verify" runs the generator and fails on any
// diff, which is what holds that guarantee.
//
// Usage:
//
//	go run ./internal/tools/docsgen
//
// The command takes no arguments. Output is written relative to the directory
// holding go.mod, so the working directory does not decide where it lands.
//
// Nothing in the render path reads the clock, the environment, or a Go map in
// iteration order: identical inputs produce identical bytes.
package main

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// outputDir is where the rendered pages land, relative to the module root.
const outputDir = "docs/reference"

// The modes generated output is created with. The pages are committed
// alongside the source they are rendered from, so they are world readable.
const (
	filePerm = 0o644
	dirPerm  = 0o755
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "docsgen: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := moduleRoot()
	if err != nil {
		return err
	}
	m, err := readModule(root)
	if err != nil {
		return err
	}
	return generate(filepath.Join(root, filepath.FromSlash(outputDir)), m)
}

// module is what a page needs from the checkout rather than from a Go table.
type module struct {
	// goVersion is the go directive from go.mod: the toolchain a reader needs
	// to build the tree.
	goVersion string
}

// document is one rendered page.
type document struct {
	// name is the file written under [outputDir].
	name string
	// source is the Go file holding the table the page is rendered from. The
	// generated notice names it, so a reader who wants the page to say
	// something else edits the table rather than the page.
	source string
	// render writes the body, which follows the notice.
	render func(*strings.Builder, module) error
}

// documents returns the pages in the order they are written.
func documents() []document {
	return []document{
		{"cli.md", "internal/cli/cli.go", renderCommands},
		{"flags.md", "internal/config/limit.go", renderFlags},
		{"exit-codes.md", "internal/report/code.go", renderExitCodes},
		{"keys.md", "internal/ui/keys/table.go", renderKeys},
		{"diagnostics.md", "internal/diag/diag.go", renderDiagnostics},
		{"state-schema.md", "internal/agentstate/state.go", renderStateSchema},
		{"report-envelope.md", "internal/report/schema.go", renderReportEnvelope},
		{"platforms.md", "internal/tools/docsgen/platforms.go", renderPlatforms},
	}
}

// generate writes every page into dir, creating it when it does not exist.
func generate(dir string, m module) error {
	if err := os.MkdirAll(dir, dirPerm); err != nil {
		return fmt.Errorf("create %s: %w", dir, err)
	}
	for _, d := range documents() {
		var b strings.Builder
		b.WriteString(notice(d.source))
		if err := d.render(&b, m); err != nil {
			return fmt.Errorf("%s: %w", d.name, err)
		}
		path := filepath.Join(dir, d.name)
		if err := os.WriteFile(path, []byte(b.String()), filePerm); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}

// noticePrefix opens every rendered page, and is what a reader — and this
// package's own test — recognizes a generated page by.
const noticePrefix = "<!-- Generated by internal/tools/docsgen"

// notice returns the header that names the page as generated and points at the
// table it comes from.
func notice(source string) string {
	return noticePrefix + " from " + source + ". Edit that table, then run `task gen`. -->\n\n"
}

// moduleRoot returns the directory holding go.mod, found by walking up from
// the working directory. Locating the root rather than assuming it is what
// lets the generator be run from the module root, from its own package
// directory, or from anywhere else in the tree and write the same files.
func moduleRoot() (string, error) {
	start, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("read the working directory: %w", err)
	}
	for dir := start; ; {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no go.mod at or above %s", start)
		}
		dir = parent
	}
}

// readModule collects what the pages state about the checkout and holds the
// workflow to the markers the platform matrix reads as evidence.
func readModule(root string) (module, error) {
	src, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return module{}, fmt.Errorf("read go.mod: %w", err)
	}
	version, err := goDirective(string(src))
	if err != nil {
		return module{}, err
	}
	if err := checkWorkflow(root); err != nil {
		return module{}, err
	}
	return module{goVersion: version}, nil
}

// goDirective returns the version named by the go line of a go.mod.
func goDirective(src string) (string, error) {
	for line := range strings.Lines(src) {
		fields := strings.Fields(line)
		if len(fields) == 2 && fields[0] == "go" {
			return fields[1], nil
		}
	}
	return "", errors.New("go.mod declares no go directive")
}

// workflowPath holds the jobs the platform matrix reports on.
const workflowPath = ".github/workflows/ci.yml"

// workflowMarkers are the strings each matrix claim is evidence-bound to. A
// marker the workflow does not carry means the matrix asserts a property no
// job checks, so the generator stops rather than publishing it.
var workflowMarkers = []struct {
	text  string
	claim string
}{
	{"-race", "the suite runs under the race detector"},
	{"GOOS: windows", "Windows is compiled rather than tested"},
}

// checkWorkflow reports a matrix claim the workflow stopped backing.
//
// Every row of the platform matrix that claims a test run names the runner
// whose job performs it, and a runner the workflow does not carry stops the
// generator. The matrix is otherwise an assertion: a table saying the suite
// runs somewhere, written by hand, checked by nobody.
func checkWorkflow(root string) error {
	path := filepath.Join(root, filepath.FromSlash(workflowPath))
	src, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read %s, which the platform matrix reports on: %w", workflowPath, err)
	}
	text := string(src)
	for _, marker := range workflowMarkers {
		if !strings.Contains(text, marker.text) {
			return fmt.Errorf("%s carries no %q, so the matrix cannot claim that %s",
				workflowPath, marker.text, marker.claim)
		}
	}
	for _, p := range platforms {
		if p.runner == "" {
			continue
		}
		if !strings.Contains(text, p.runner) {
			return fmt.Errorf("the matrix claims the suite runs on %s, and %s names no %q runner",
				p.name, workflowPath, p.runner)
		}
	}
	return nil
}
